export  enum DegreeType {
  HIGH_SCHOOL_DIPLOMA = 'HIGH_SCHOOL_DIPLOMA',
  SSC = 'SSC',
  HSC = 'HSC',
  ASSOCIATE = 'ASSOCIATE',
  BACHELOR = 'BACHELOR',
  MASTER = 'MASTER',
  DOCTORAL = 'DOCTORAL',
  LAW = 'LAW',
  MEDICAL = 'MEDICAL',
  MBA = 'MBA',
  MED = 'MED',
  PHD = 'PHD',
  OTHER = 'OTHER'
}
